In [5]:
import cv2
import numpy as np
 
img_path = r"C:\Users\Savita Seharawat\Desktop\fulhaus\Dog+and+Cat.jpg"
 
image = cv2.imread(img_path)
image = cv2.resize(image, (1280, 720))

 
cv2.imshow("Rectangle on Image", image)
 
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
image

array([[[160, 162, 172],
        [161, 163, 173],
        [162, 164, 174],
        ...,
        [  0,  46,  32],
        [  0,  50,  36],
        [  1,  55,  40]],

       [[208, 211, 219],
        [208, 212, 217],
        [209, 212, 220],
        ...,
        [  0,  46,  32],
        [  1,  51,  34],
        [  4,  56,  39]],

       [[208, 213, 217],
        [208, 213, 217],
        [208, 213, 217],
        ...,
        [  0,  40,  25],
        [  1,  45,  30],
        [  6,  50,  35]],

       ...,

       [[139, 181, 206],
        [138, 180, 205],
        [137, 179, 205],
        ...,
        [153, 187, 203],
        [153, 187, 202],
        [153, 187, 202]],

       [[138, 181, 208],
        [138, 181, 208],
        [138, 181, 208],
        ...,
        [156, 190, 206],
        [156, 190, 206],
        [156, 190, 206]],

       [[145, 188, 215],
        [145, 189, 216],
        [146, 189, 216],
        ...,
        [154, 188, 204],
        [154, 188, 203],
        [154, 188, 203]]

In [4]:
image.shape

(720, 1280, 3)

In [6]:
image[:,:,0]

array([[160, 161, 162, ...,   0,   0,   1],
       [208, 208, 209, ...,   0,   1,   4],
       [208, 208, 208, ...,   0,   1,   6],
       ...,
       [139, 138, 137, ..., 153, 153, 153],
       [138, 138, 138, ..., 156, 156, 156],
       [145, 145, 146, ..., 154, 154, 154]], dtype=uint8)

In [7]:
image[:,:,1]

array([[162, 163, 164, ...,  46,  50,  55],
       [211, 212, 212, ...,  46,  51,  56],
       [213, 213, 213, ...,  40,  45,  50],
       ...,
       [181, 180, 179, ..., 187, 187, 187],
       [181, 181, 181, ..., 190, 190, 190],
       [188, 189, 189, ..., 188, 188, 188]], dtype=uint8)

In [8]:
image[:,:,2]

array([[172, 173, 174, ...,  32,  36,  40],
       [219, 217, 220, ...,  32,  34,  39],
       [217, 217, 217, ...,  25,  30,  35],
       ...,
       [206, 205, 205, ..., 203, 202, 202],
       [208, 208, 208, ..., 206, 206, 206],
       [215, 216, 216, ..., 204, 203, 203]], dtype=uint8)

In [6]:
import cv2
import numpy as np
 
img_path = r"C:\Users\Savita Seharawat\Desktop\fulhaus\Dog+and+Cat.jpg"
 
image = cv2.imread(img_path)
image = cv2.resize(image, (1280, 720))
img_gray = cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
cv2.imshow("Rectangle on Image", img_gray)  
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
import cv2
import numpy as np
 
img_path = r"C:\Users\Savita Seharawat\Desktop\fulhaus\Dog+and+Cat.jpg"
 
image = cv2.imread(img_path)
image = cv2.resize(image, (1280, 720))
img_gray = cv2.cvtColor(image,cv2.COLOR_BGR2Luv)
cv2.imshow("Rectangle on Image", img_gray)  
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
cv2.COLOR_BGR2Luv

50

In [5]:
import cv2
import numpy as np
 
img_path = r"C:\Users\Savita Seharawat\Desktop\fulhaus\Dog+and+Cat.jpg"
 
image = cv2.imread(img_path)
image = cv2.resize(image, (1280, 720))
img_gray = cv2.cvtColor(image,cv2.COLOR_BGR2Luv)
cv2.imshow("Rectangle on Image", img_gray)  
cv2.waitKey(0)
cv2.destroyAllWindows()

In [1]:
import cv2 
Color_name = [i for i in dir(cv2) if i.startswith('COLOR_BGR2')]
print( Color_name )

['COLOR_BGR2BGR555', 'COLOR_BGR2BGR565', 'COLOR_BGR2BGRA', 'COLOR_BGR2GRAY', 'COLOR_BGR2HLS', 'COLOR_BGR2HLS_FULL', 'COLOR_BGR2HSV', 'COLOR_BGR2HSV_FULL', 'COLOR_BGR2LAB', 'COLOR_BGR2LUV', 'COLOR_BGR2Lab', 'COLOR_BGR2Luv', 'COLOR_BGR2RGB', 'COLOR_BGR2RGBA', 'COLOR_BGR2XYZ', 'COLOR_BGR2YCR_CB', 'COLOR_BGR2YCrCb', 'COLOR_BGR2YUV', 'COLOR_BGR2YUV_I420', 'COLOR_BGR2YUV_IYUV', 'COLOR_BGR2YUV_UYNV', 'COLOR_BGR2YUV_UYVY', 'COLOR_BGR2YUV_Y422', 'COLOR_BGR2YUV_YUNV', 'COLOR_BGR2YUV_YUY2', 'COLOR_BGR2YUV_YUYV', 'COLOR_BGR2YUV_YV12', 'COLOR_BGR2YUV_YVYU']


In [11]:
Color_name = [ cv2.COLOR_BGR2Luv, cv2.COLOR_BGR2GRAY,cv2.COLOR_BGR2LUV,cv2.COLOR_BGR2YCrCb,cv2.COLOR_BGR2Lab,cv2.COLOR_BGR2HLS_FULL]

In [16]:
import cv2
import numpy as np
 
img_path = r"C:\Users\Savita Seharawat\Desktop\fulhaus\Dog+and+Cat.jpg"
 
image = cv2.imread(img_path)
image = cv2.resize(image, (1280, 720))
for color_number in Color_name:
    color_image = cv2.cvtColor(image,color_number)
    cv2.imshow(f"image *{color_number}*", color_image)
    cv2.waitKey(2000) # pause for 2 seconds
    cv2.destroyAllWindows()
    
    